spring.application.name=cliente

spring.dataresource.url=jdbc=mysql://localhost:3306/crud_clientes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.dataresource.username=root
spring.dataresource.password = 

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
