version: '3.9'
services:
  db_data:
    image: mysql:8.0
    container_name: mysql-db-fatec
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: fatec
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
